// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXSa9awAf9fE_IVy0xK1glBcd_rqWWEQ4',
    appId: '1:201624206314:web:fd182038c20ec5a6465093',
    messagingSenderId: '201624206314',
    projectId: 'ecommerce-62f68',
    authDomain: 'ecommerce-62f68.firebaseapp.com',
    storageBucket: 'ecommerce-62f68.appspot.com',
    measurementId: 'G-HSGQT5Z0LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTDnvB-SBT61_-gmYubj44CBayhXAWSA',
    appId: '1:201624206314:android:5543286b9119ed7d465093',
    messagingSenderId: '201624206314',
    projectId: 'ecommerce-62f68',
    storageBucket: 'ecommerce-62f68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDydMn1pl3rikP-KPmD1oCTqvBefu1Ic',
    appId: '1:201624206314:ios:4c51d1b0a212a785465093',
    messagingSenderId: '201624206314',
    projectId: 'ecommerce-62f68',
    storageBucket: 'ecommerce-62f68.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdDydMn1pl3rikP-KPmD1oCTqvBefu1Ic',
    appId: '1:201624206314:ios:81fa23208d543cd8465093',
    messagingSenderId: '201624206314',
    projectId: 'ecommerce-62f68',
    storageBucket: 'ecommerce-62f68.appspot.com',
    iosBundleId: 'com.example.project2.RunnerTests',
  );
}
